### ISSUE TITLE
Install all required packages 

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/academy#15]
0. ```git clone -b dev https://github.com/fuchicorp/webplatform.git```
1. Install python3
2. Install virtualenvwrapper  [follow the docs](https://virtualenvwrapper.readthedocs.io/en/latest/)
3. ```mkvirtualenv --python=`which python3` fuchicorp ```
4.  ```cd webplatform ```
5. ```pip install -r requirements.txt``` (if you see an error please delete mysqlclient from requirements.txt)
6. ```mkdir /Users/$(whoami)/backup/databases/ -p ```
7.  ```sqlite3 /Users/$(whoami)/backup/databases/webplatform.db```

```
~/Projects/fuchicorp-projects/webplatform(dev) » sqlite3 /Users/$(whoami)/backup/databases/webplatform.db 
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> .tables
message  pynote   user
sqlite> .exit
```
8. `python app.py --debug`

**Comment by ChoroHappy** [comment]
Hello sir,

1) on the step 0. im getting the following error:
$ git clone -b dev https://github.com/fuchicorp/webplatform.git
Cloning into 'webplatform'...
fatal: Remote branch dev not found in upstream origin

2) on the step 3.:
$ mkvirtualenv --python=`which python3` fuchicorp
bash: mkvirtualenv: command not found

3) how do i use the information you send me on Slack?

Thank you in advance and kind regards
Choro

пт, 3 апр. 2020 г. в 07:45, Farkhod Sadykov <notifications@github.com>:
